// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

import { D1Database } from "@cloudflare/workers-types";

declare global {
  interface CloudflareEnv {
    DB: D1Database;
    R2_ENDPOINT: string;
    R2_ACCESS_KEY_ID: string;
    R2_SECRET_ACCESS_KEY: string;
    R2_BUCKET_NAME: string;
    R2_PUBLIC_URL: string;
    DISCORD_GUILD_ID: string;
    DISCORD_BOT_TOKEN: string;
    DISCORD_FORUM_CHANNEL_ID: string;
    DISCORD_WEBHOOK_URL: string;
  }
}
