// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

import { D1Database } from "@cloudflare/workers-types";

declare global {
  interface CloudflareEnv {
    DB: D1Database;
    CLOUDFLARE_R2_ENDPOINT: string;
    CLOUDFLARE_R2_ACCESS_KEY_ID: string;
    CLOUDFLARE_R2_SECRET_ACCESS_KEY: string;
    CLOUDFLARE_R2_BUCKET_NAME: string;
  }
}
